[vtpm.config]
qemu="/usr/mvp/bin/qemu-system-x86_64"
vtpm_td_script = "launch_vtpm_td.sh"
user_td_script = "launch_user_td.sh"
vtpm_td_bios_img = "/home/mxu9/workspace/test/run-vtpm-td/vtpmtd.bin"
user_td_bios_img = "/home/mxu9/workspace/test/run-user-td/OVMF.fd"
kernel_img = "/home/mxu9/workspace/test/media/vmlinuz-jammy"
guest_img = "/home/mxu9/workspace/test/media/td-guest-ubuntu-22.04-test.qcow2"
guest_username = "root"
guest_password = "123456"
vtpm_test_img = "/home/mxu9/workspace/test/vtpm.img"
vtpm_test_img_mount_path = "//home/mxu9/workspace/test/vtpm"
default_user_id = "aabbccdd-2008-2022-1234-123456789123"
default_startup_cmds = [
  "fs0:",
]
stress_test_cycles = 100
default_wait_tools_run_seconds = 20
